name: Feature request
description: Suggest an improvement or new capability
title: "Feature: "
labels:
  - enhancement
assignees:
  - taurgis
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Please include device and version details so we can assess feasibility.

  - type: input
    id: ha_version
    attributes:
      label: Home Assistant version
      placeholder: "e.g., 2026.1.5"
    validations:
      required: true

  - type: input
    id: component_version
    attributes:
      label: Marstek integration version
      placeholder: "e.g., 1.4.2"
    validations:
      required: true

  - type: input
    id: device_model
    attributes:
      label: Marstek device model
      placeholder: "e.g., Venus E 3.0"
    validations:
      required: true

  - type: input
    id: firmware_version
    attributes:
      label: Marstek firmware version
      placeholder: "e.g., 144"
    validations:
      required: true

  - type: textarea
    id: request
    attributes:
      label: Feature request
      description: What would you like to see added or changed?
      placeholder: "Describe the feature you want"
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: How would this help your setup or workflow?
      placeholder: "Describe your use case"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches?
      placeholder: "Describe any alternatives you've considered"
